#!/usr/bin/expect -f
set timeout 60
set password "Sipanda123#"
spawn scp -o StrictHostKeyChecking=no /Users/pondokit/Herd/retribusi-api/retribusi-frontend-dev.conf sipanda@157.10.252.74:/tmp/retribusi-frontend-dev.conf
expect "password:"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password\r"
expect "$ "
send "sudo mv /tmp/retribusi-frontend-dev.conf /etc/nginx/sites-available/retribusi-frontend-dev\r"
expect "password for sipanda:"
send "$password\r"
expect "$ "
send "sudo ln -s /etc/nginx/sites-available/retribusi-frontend-dev /etc/nginx/sites-enabled/retribusi-frontend-dev\r"
expect "$ "
send "sudo mkdir -p /home/sipanda/retribusi-admin-dev/dist /home/sipanda/retribusi-petugas-dev/dist /home/sipanda/retribusi-mobile-dev/dist\r"
expect "$ "
send "sudo chown -R sipanda:sipanda /home/sipanda/retribusi-admin-dev /home/sipanda/retribusi-petugas-dev /home/sipanda/retribusi-mobile-dev\r"
expect "$ "
send "sudo nginx -t && sudo systemctl reload nginx\r"
expect "$ "
send "exit\r"
expect eof
