server {
    server_name sipanda.online;
    root /home/sipanda/retribusi-mobile-staging/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    server_name admin.sipanda.online;
    root /home/sipanda/retribusi-admin-staging/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    server_name petugas.sipanda.online;
    root /home/sipanda/retribusi-petugas-staging/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    server_name api.sipanda.online;
    root /home/sipanda/retribusi-api-staging/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }
}

server {
    server_name pos.sipanda.online;
    root /home/sipanda/retribusi-pos-staging;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    server_name api-pos.sipanda.online;
    root /home/sipanda/retribusi-pos-staging/backend/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }
}
