server {
    listen 80;
    server_name sipanda.online www.sipanda.online;
    root /home/sipanda/retribusi-mobile/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}

server {
    listen 80;
    server_name admin.sipanda.online;
    root /home/sipanda/retribusi-admin/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}

server {
    listen 80;
    server_name petugas.sipanda.online;
    root /home/sipanda/retribusi-petugas/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
