#!/usr/bin/expect -f
set timeout 10
spawn ssh sipanda@157.10.252.74 -t "sudo chown -R www-data:www-data /home/sipanda/retribusi-api-dev/storage /home/sipanda/retribusi-api-dev/bootstrap/cache && sudo chmod -R 775 /home/sipanda/retribusi-api-dev/storage /home/sipanda/retribusi-api-dev/bootstrap/cache"
expect "password:"
send "Sipanda123#\r"

expect {
    "password for sipanda:" {
        send "Sipanda123#\r"
        exp_continue
    }
    eof
}
