#!/usr/bin/expect -f
set timeout 30
set password "[REDACTED]"
set host "157.10.252.74"
set user "sipanda"

# Read local file content
set fp [open "/Users/pondokit/Herd/retribusi-api/retribusi-frontend-prod.conf" r]
set file_data [read $fp]
close $fp

spawn ssh $user@$host "cat > /home/sipanda/retribusi-frontend-prod.conf && sudo mv /home/sipanda/retribusi-frontend-prod.conf /etc/nginx/sites-available/retribusi-frontend-prod && sudo ln -sf /etc/nginx/sites-available/retribusi-frontend-prod /etc/nginx/sites-enabled/retribusi-frontend-prod && sudo nginx -t && sudo systemctl reload nginx"
expect "password:"
send "$password\r"
expect "sipanda:"
send "$password\r"
expect eof
