#!/usr/bin/expect -f
set timeout 30
set password "Sipanda123#"
spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password\r"
expect "$ "
send "cat /etc/nginx/sites-enabled/retribusi-frontend-dev\r"
expect "$ "
send "cat /etc/nginx/sites-enabled/retribusi-frontend\r"
expect "$ "
send "find /home/sipanda -name index.html -not -path '*/node_modules/*'\r"
expect "$ "
send "exit\r"
expect eof
