#!/usr/bin/expect -f
set timeout 300
set pass "Sipanda123#"

spawn ssh sipanda@157.10.252.74
expect "password:"
send "$pass\r"
expect -re {[\$#] }

send "cd /home/sipanda/retribusi-api\r"
expect -re {[\$#] }

send "sudo git fetch --all\r"
expect {
    "password" { send "$pass\r"; exp_continue }
    -re {[\$#] }
}

send "sudo git reset --hard origin/dev\r"
expect -re {[\$#] }

send "sudo chown -R www-data:www-data storage bootstrap/cache\r"
expect -re {[\$#] }

send "sudo chmod -R 775 storage bootstrap/cache\r"
expect -re {[\$#] }

send "composer install --no-dev --optimize-autoloader\r"
expect -re {[\$#] }

send "php artisan migrate --force\r"
expect -re {[\$#] }

send "sudo -u www-data php artisan optimize\r"
expect -re {[\$#] }

send "exit\r"
expect eof
