#!/usr/bin/expect -f
set timeout 15
set password "Sipanda123#"
spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password"
expect "$ "
send "ls -la /etc/nginx/sites-enabled/ && grep -r \"dev.sipanda.online\" /etc/nginx/sites-available/"
expect "$ "
send "exit"
expect eof
spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password"
expect "$ "
send "grep -r \"server_name\" /etc/nginx/sites-enabled/"
expect "$ "
send "exit"
expect eof
