#!/usr/bin/expect -f
set timeout 120
set password "[REDACTED]"
set host "157.10.252.74"
set user "sipanda"

spawn ssh $user@$host "sudo certbot --nginx -d sipanda.online -d www.sipanda.online -d admin.sipanda.online -d petugas.sipanda.online --non-interactive --agree-tos --email admin@sipanda.online"
expect "password:"
send "$password\r"
expect {
    "password:" { send "$password\r"; exp_continue }
    eof
}
