#!/usr/bin/expect -f
set timeout 15
set password "Sipanda123#"
spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password\r"
expect "$ "
send "touch /home/sipanda/retribusi-admin-dev/dist/test_write\r"
expect "$ "
send "ls -la /home/sipanda/retribusi-admin-dev/dist/test_write\r"
expect "$ "
send "touch /home/sipanda/retribusi-petugas-dev/dist/test_write\r"
expect "$ "
send "ls -la /home/sipanda/retribusi-petugas-dev/dist/test_write\r"
expect "$ "
send "exit\r"
expect eof
