#!/usr/bin/expect -f
set timeout 30
set password "Sipanda123#"
spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password\r"
expect "$ "
send "ls -la /home/sipanda/retribusi-admin-dev/dist /home/sipanda/retribusi-petugas-dev/dist /home/sipanda/retribusi-mobile-dev/dist\r"
expect "$ "
send "sudo tail -n 20 /var/log/nginx/error.log\r"
expect "password for sipanda:"
send "$password\r"
expect "$ "
send "exit\r"
expect eof
