#!/usr/bin/expect -f
set timeout 15
set password "Sipanda123#"
spawn ssh -o StrictHostKeyChecking=no sipanda@157.10.252.74
expect "password:"
send "$password\r"
expect "$ "
send "sudo rm -rf /home/sipanda/retribusi-admin-dev/dist /home/sipanda/retribusi-petugas-dev/dist /home/sipanda/retribusi-mobile-dev/dist\r"
expect "password for sipanda:"
send "$password\r"
expect "$ "
send "mkdir -p /home/sipanda/retribusi-admin-dev/dist /home/sipanda/retribusi-petugas-dev/dist /home/sipanda/retribusi-mobile-dev/dist\r"
expect "$ "
send "sudo chown -R sipanda:sipanda /home/sipanda/retribusi-admin-dev /home/sipanda/retribusi-petugas-dev /home/sipanda/retribusi-mobile-dev\r"
expect "$ "
send "sudo chmod -R 755 /home/sipanda/retribusi-admin-dev /home/sipanda/retribusi-petugas-dev /home/sipanda/retribusi-mobile-dev\r"
expect "$ "
send "exit\r"
expect eof
